// Mock data para catálogo de destajistas
export const destajistasMock = [
  { inicial: "AG", nombre: "Abraham Garcia", color: "#b91c1c", especialidad: "Fierrero" },
  { inicial: "AR", nombre: "Angel Rangel", color: "#1e40af", especialidad: "Bloquero" },
  { inicial: "AC", nombre: "Arturo Carmona", color: "#15803d", especialidad: "Yesero" },
  { inicial: "BO", nombre: "Bacilio Ortiz", color: "#a21caf", especialidad: "Fierrero" },
  { inicial: "BG", nombre: "Benito Garcia", color: "#c2410c", especialidad: "Bloquero" },
  { inicial: "EMR", nombre: "Edwin Medina", color: "#0891b2", especialidad: "Instalador" },
  { inicial: "EL", nombre: "Eleazar Leon", color: "#4f46e5", especialidad: "Yesero" },
  { inicial: "EM", nombre: "Emanuel Martinez", color: "#be123c", especialidad: "Fierrero" },
  { inicial: "FR", nombre: "Fabian Rodriguez", color: "#0d9488", especialidad: "Bloquero" },
  { inicial: "FB", nombre: "Facundo Bautista", color: "#7c3aed", especialidad: "Yesero" },
  { inicial: "FS", nombre: "Fernando Sanchez", color: "#dc2626", especialidad: "Fierrero" },
  { inicial: "FT", nombre: "Fidel Tinajero", color: "#2563eb", especialidad: "Instalador" },
  { inicial: "FM", nombre: "Francisco Martínez", color: "#16a34a", especialidad: "Bloquero" },
  { inicial: "FV", nombre: "Francisco Valencia", color: "#9333ea", especialidad: "Yesero" },
  { inicial: "IDP", nombre: "IDP", color: "#334155", especialidad: "Varios" },
  { inicial: "JB", nombre: "Juan Briones", color: "#ea580c", especialidad: "Fierrero" },
  { inicial: "LJ", nombre: "Laura Juarez", color: "#0284c7", especialidad: "Acabados" },
  { inicial: "MA", nombre: "Marco Angeles", color: "#059669", especialidad: "Bloquero" },
  { inicial: "ML", nombre: "Miguel Lopez", color: "#7c2d12", especialidad: "Yesero" },
  { inicial: "OS", nombre: "Octaviano Sandoval", color: "#1e3a8a", especialidad: "Fierrero" },
  { inicial: "OR", nombre: "Oscar Rizo", color: "#14532d", especialidad: "Instalador" },
  { inicial: "OSU", nombre: "Oscar Suarez", color: "#86198f", especialidad: "Bloquero" },
  { inicial: "RB", nombre: "Remedios Bautista", color: "#be185d", especialidad: "Acabados" },
  { inicial: "RF", nombre: "Roberto Flores", color: "#0369a1", especialidad: "Yesero" },
  { inicial: "RO", nombre: "Roberto Ortiz Sanchez", color: "#047857", especialidad: "Fierrero" },
  { inicial: "RR", nombre: "Roberto Reyes", color: "#b45309", especialidad: "Bloquero" },
  { inicial: "SC", nombre: "Samuel Chico", color: "#6366f1", especialidad: "Instalador" },
  { inicial: "SL", nombre: "Severo Luciano", color: "#ca8a04", especialidad: "Yesero" },
  { inicial: "BJ", nombre: "Benjamin Juarez", color: "#0e7490", especialidad: "Fierrero" },
  { inicial: "RA", nombre: "Ricardo de Alba", color: "#991b1b", especialidad: "Bloquero" },
  { inicial: "RM", nombre: "Ronaldo Martinez", color: "#166534", especialidad: "Acabados" },
  { inicial: "IG", nombre: "Isidro Garcia", color: "#7e22ce", especialidad: "Yesero" },
];
