// Mock data para obras con destajos asignados
export const obrasMock = [
  {
    id: "1",
    nombre: "CASTELLO F",
    nombreCompleto: "CASTELLO F - Fraccionamiento Residencial Meseta",
    codigo: "228",
    cliente: "Residencial Meseta SA de CV",
    ubicacion: "Av. Meseta Sur 4500, Aguascalientes",
    estado: "En Proceso",
    progreso: 68,
    presupuesto: 4500000,
    gastado: 3060000,
    destajos: [
      {
        id: "d1",
        fecha: "2024-02-01",
        lote: "L-001",
        descripcion: "Cimentación y desplante",
        categoria: "Estructura",
        unidad: "m²",
        cantidad: 85,
        precioUnitario: 350,
        destajista: "JP",
      },
      {
        id: "d2",
        fecha: "2024-02-03",
        lote: "L-002",
        descripcion: "Muros de carga",
        categoria: "Albañilería",
        unidad: "m²",
        cantidad: 120,
        precioUnitario: 280,
        destajista: "MG",
      },
      {
        id: "d3",
        fecha: "2024-02-05",
        lote: "L-003",
        descripcion: "Instalación eléctrica",
        categoria: "Instalaciones",
        unidad: "salida",
        cantidad: 45,
        precioUnitario: 420,
        destajista: "CR",
      },
      {
        id: "d4",
        fecha: "2024-02-07",
        lote: "L-004",
        descripcion: "Acabados interiores",
        categoria: "Acabados",
        unidad: "m²",
        cantidad: 95,
        precioUnitario: 380,
        destajista: "AL",
      },
    ],
  },
  {
    id: "2",
    nombre: "CASTELLO G",
    nombreCompleto: "CASTELLO G - Fraccionamiento Residencial Meseta",
    codigo: "229",
    cliente: "Residencial Meseta SA de CV",
    ubicacion: "Av. Meseta Sur 4502, Aguascalientes",
    estado: "En Proceso",
    progreso: 72,
    presupuesto: 4800000,
    gastado: 3456000,
    destajos: [
      {
        id: "d5",
        fecha: "2024-02-02",
        lote: "L-005",
        descripcion: "Estructura de concreto",
        categoria: "Estructura",
        unidad: "m³",
        cantidad: 65,
        precioUnitario: 1200,
        destajista: "JP",
      },
      {
        id: "d6",
        fecha: "2024-02-04",
        lote: "L-006",
        descripcion: "Instalación hidráulica",
        categoria: "Instalaciones",
        unidad: "salida",
        cantidad: 38,
        precioUnitario: 550,
        destajista: "LM",
      },
      {
        id: "d7",
        fecha: "2024-02-06",
        lote: "L-007",
        descripcion: "Pintura y acabados",
        categoria: "Acabados",
        unidad: "m²",
        cantidad: 110,
        precioUnitario: 180,
        destajista: "SF",
      },
    ],
  },
  {
    id: "3",
    nombre: "CASTELLO H",
    nombreCompleto: "CASTELLO H - Fraccionamiento Residencial Meseta",
    codigo: "230",
    cliente: "Residencial Meseta SA de CV",
    ubicacion: "Av. Meseta Sur 4504, Aguascalientes",
    estado: "En Proceso",
    progreso: 55,
    presupuesto: 4600000,
    gastado: 2530000,
    destajos: [
      {
        id: "d8",
        fecha: "2024-02-01",
        lote: "L-008",
        descripcion: "Firmes y contrapisos",
        categoria: "Estructura",
        unidad: "m²",
        cantidad: 140,
        precioUnitario: 220,
        destajista: "MG",
      },
      {
        id: "d9",
        fecha: "2024-02-03",
        lote: "L-009",
        descripcion: "Herrería y cancelería",
        categoria: "Acabados",
        unidad: "pieza",
        cantidad: 28,
        precioUnitario: 2500,
        destajista: "CR",
      },
      {
        id: "d10",
        fecha: "2024-02-05",
        lote: "L-010",
        descripcion: "Azulejos y pisos",
        categoria: "Acabados",
        unidad: "m²",
        cantidad: 88,
        precioUnitario: 450,
        destajista: "DR",
      },
    ],
  },
  {
    id: "4",
    nombre: "DOZA A",
    nombreCompleto: "DOZA A - Conjunto Habitacional Valle Verde",
    codigo: "231",
    cliente: "Inmobiliaria Valle Verde",
    ubicacion: "Blvd. Valle Verde 2100, Aguascalientes",
    estado: "En Proceso",
    progreso: 61,
    presupuesto: 3800000,
    gastado: 2318000,
    destajos: [
      {
        id: "d11",
        fecha: "2024-02-02",
        lote: "L-011",
        descripcion: "Excavación y cimentación",
        categoria: "Estructura",
        unidad: "m³",
        cantidad: 55,
        precioUnitario: 850,
        destajista: "AL",
      },
      {
        id: "d12",
        fecha: "2024-02-04",
        lote: "L-012",
        descripcion: "Muebles de baño",
        categoria: "Acabados",
        unidad: "pieza",
        cantidad: 18,
        precioUnitario: 3200,
        destajista: "JP",
      },
      {
        id: "d13",
        fecha: "2024-02-06",
        lote: "L-013",
        descripcion: "Sistema eléctrico",
        categoria: "Instalaciones",
        unidad: "salida",
        cantidad: 52,
        precioUnitario: 380,
        destajista: "VC",
      },
    ],
  },
  {
    id: "5",
    nombre: "DOZA C",
    nombreCompleto: "DOZA C - Conjunto Habitacional Valle Verde",
    codigo: "232",
    cliente: "Inmobiliaria Valle Verde",
    ubicacion: "Blvd. Valle Verde 2102, Aguascalientes",
    estado: "En Proceso",
    progreso: 48,
    presupuesto: 3900000,
    gastado: 1872000,
    destajos: [
      {
        id: "d14",
        fecha: "2024-02-01",
        lote: "L-014",
        descripcion: "Techos y losas",
        categoria: "Estructura",
        unidad: "m²",
        cantidad: 105,
        precioUnitario: 580,
        destajista: "LM",
      },
      {
        id: "d15",
        fecha: "2024-02-03",
        lote: "L-015",
        descripcion: "Carpintería fina",
        categoria: "Acabados",
        unidad: "pieza",
        cantidad: 22,
        precioUnitario: 2800,
        destajista: "SF",
      },
      {
        id: "d16",
        fecha: "2024-02-05",
        lote: "L-016",
        descripcion: "Jardinería y áreas verdes",
        categoria: "Exteriores",
        unidad: "m²",
        cantidad: 75,
        precioUnitario: 320,
        destajista: "MG",
      },
    ],
  },
  {
    id: "6",
    nombre: "BALVANERA",
    nombreCompleto: "BALVANERA - Desarrollo Urbano Sustentable",
    codigo: "233",
    cliente: "Grupo Balvanera Desarrollos",
    ubicacion: "Av. Tecnológico 950, Aguascalientes",
    estado: "En Proceso",
    progreso: 75,
    presupuesto: 5200000,
    gastado: 3900000,
    destajos: [
      {
        id: "d17",
        fecha: "2024-02-02",
        lote: "L-017",
        descripcion: "Terrazas y balcones",
        categoria: "Estructura",
        unidad: "m²",
        cantidad: 92,
        precioUnitario: 680,
        destajista: "CR",
      },
      {
        id: "d18",
        fecha: "2024-02-04",
        lote: "L-018",
        descripcion: "Aire acondicionado",
        categoria: "Instalaciones",
        unidad: "equipo",
        cantidad: 16,
        precioUnitario: 4500,
        destajista: "DR",
      },
      {
        id: "d19",
        fecha: "2024-02-06",
        lote: "L-019",
        descripcion: "Iluminación decorativa",
        categoria: "Acabados",
        unidad: "punto",
        cantidad: 48,
        precioUnitario: 850,
        destajista: "VC",
      },
      {
        id: "d20",
        fecha: "2024-02-08",
        lote: "L-020",
        descripcion: "Puertas y ventanas",
        categoria: "Acabados",
        unidad: "pieza",
        cantidad: 35,
        precioUnitario: 1800,
        destajista: "AL",
      },
    ],
  },
];
