// Mock data para obras del dashboard global
export const obrasDashboardMock = [
  {
    code: "228",
    name: "CASTELLO F - Fraccionamiento Residencial Meseta",
    client: "Melisa Leal",
    contractAmount: 5250000,
    actualBalance: 1575000,
    totalEstimates: 2100000,
    totalExpenses: 525000,
    resident: "RUBA - Guanajuato, Apaseo El Grande",
    status: "Activa" as const,
  },
  {
    code: "229",
    name: "CASTELLO G - Fraccionamiento Residencial Meseta",
    client: "Melisa Leal",
    contractAmount: 4800000,
    actualBalance: 1440000,
    totalEstimates: 1920000,
    totalExpenses: 480000,
    resident: "RUBA - Guanajuato, Apaseo El Grande",
    status: "Activa" as const,
  },
  {
    code: "230",
    name: "CASTELLO H - Fraccionamiento Residencial Meseta",
    client: "Arq. Juan Carbon",
    contractAmount: 5100000,
    actualBalance: 1530000,
    totalEstimates: 2040000,
    totalExpenses: 510000,
    resident: "RUBA - Guanajuato, Apaseo El Grande",
    status: "Activa" as const,
  },
  {
    code: "231",
    name: "DOZA A - Fraccionamiento Residencial Mayorazgo",
    client: "Sergio Guerrero",
    contractAmount: 6700000,
    actualBalance: 2010000,
    totalEstimates: 2680000,
    totalExpenses: 670000,
    resident: "Atlas - Queretaro, Queretaro",
    status: "Activa" as const,
  },
  {
    code: "232",
    name: "BALVANERA - LOTE 25 ETAPA FRACC. PRIVADA PALERMO",
    client: "Violeta Valdivia",
    contractAmount: 8900000,
    actualBalance: 2670000,
    totalEstimates: 3560000,
    totalExpenses: 890000,
    resident: "Antonio Chavez Garcia - Queretaro, Queretaro",
    status: "Activa" as const,
  },
  {
    code: "233",
    name: "DOZA C - Fraccionamiento Residencial Mayorazgo",
    client: "Sergio Guerrero",
    contractAmount: 6500000,
    actualBalance: 1950000,
    totalEstimates: 2600000,
    totalExpenses: 650000,
    resident: "ATLAS - Queretaro, El Marquez",
    status: "Activa" as const,
  },
];
